---

- name: Install redis server
  ansible.builtin.apt:
    name: redis-server
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Deploy config
  ansible.builtin.template:
    src: redis_conf.j2
    dest: /etc/redis/redis.conf
    mode: "0640"
    owner: redis
    group: redis
  notify:
    - Restart redis
    - Enable redis
